from flask import Flask, request, jsonify
from flask_cors import CORS  # ➕ ajouter ça
import difflib
import unicodedata

app = Flask(__name__)
CORS(app)  # ➕ autorise toutes les origines (ou configure si besoin)

# 🔧 Nettoyage du texte
def nettoyer(text):
    text = text.lower().strip()
    text = ''.join(
        c for c in unicodedata.normalize('NFD', text)
        if unicodedata.category(c) != 'Mn'
    )
    return text

# ✅ Données FAQ
faq_data = [
    {"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."}, 
{"instruction": "À qui est destiné le crédit ?", "output": "Le crédit est exclusivement réservé aux salariés en contrat actif chez Talan."},
{"instruction": "Puis-je demander un crédit si je suis en période d’essai ?", "output": "Non, les demandes de crédit sont acceptées uniquement après validation de la période d’essai."},
{"instruction": "Quels sont les types de crédit disponibles ?", "output": "Crédit immobilier (1–10 ans, 5%), crédit auto (1–5 ans, 3%), crédit personnel (1–3 ans, 1%)."},
{"instruction": "Quelle est la différence entre les trois types de crédits ?", "output": "Le crédit immobilier concerne les biens immobiliers, l'auto pour l’achat d’un véhicule, et le personnel pour des besoins individuels (santé, voyage, etc.)."},
{"instruction": "Le crédit personnel peut-il être utilisé pour acheter une voiture ?", "output": "Non, l’achat de véhicule nécessite un crédit auto spécifique."},
{"instruction": "Puis-je faire une simulation de crédit ?", "output": "Oui, une simulation est disponible sur l’espace employé via le portail Talan."},
{"instruction": "Quel est le taux d’intérêt du crédit immobilier ?", "output": "5% sur une durée de 1 à 10 ans."},
{"instruction": "Quel est le taux d’un crédit auto ?", "output": "3% sur une durée de 1 à 5 ans."},
{"instruction": "Quel est le taux d’un crédit personnel ?", "output": "1% sur une durée de 1 à 3 ans."},
{"instruction": "Quels documents dois-je fournir ?", "output": "Carte d’identité (CIN), trois derniers relevés bancaires, facture ou attestation liée au crédit, fiche de paie récente."},
{"instruction": "Quels sont les justificatifs pour un prêt immobilier ?", "output": "Une promesse de vente, contrat préliminaire ou devis de construction est requis en plus des pièces standards."},
{"instruction": "Que faut-il pour un crédit auto ?", "output": "Facture pro forma ou devis du véhicule à financer, en plus des autres pièces."},
{"instruction": "Quels justificatifs pour un prêt personnel ?", "output": "Une attestation de besoin (frais médicaux, études, voyage) est recommandée."},
{"instruction": "Puis-je obtenir plusieurs crédits à la fois ?", "output": "Non, un seul crédit peut être actif par employé à la fois."},
{"instruction": "Est-ce que les intérimaires ou freelances peuvent en bénéficier ?", "output": "Non, seuls les salariés en CDI chez Talan sont éligibles."},
{"instruction": "Que se passe-t-il en cas de départ de l’entreprise ?", "output": "Le crédit devient immédiatement exigible ou doit être renégocié avec les ressources humaines."},
{"instruction": "Combien de temps prend le traitement d’une demande ?", "output": "En moyenne 5 jours ouvrés après la réception complète du dossier."},
{"instruction": "Puis-je transmettre mes documents par email ?", "output": "Oui, les documents peuvent être scannés et envoyés via l’interface RH ou par mail sécurisé."},
{"instruction": "Qui valide ma demande de crédit ?", "output": "Le service RH et la direction financière valident conjointement chaque dossier."},
{"instruction": "Puis-je rembourser plus tôt que prévu ?", "output": "Oui, un remboursement anticipé est possible sans pénalité."},
{"instruction": "Puis-je demander un crédit pendant mon congé ?", "output": "Oui, tant que vous êtes toujours salarié actif chez Talan."},
{"instruction": "Comment suis-je informé de l’avancement de ma demande ?", "output": "Vous recevrez un email ou une notification sur l’espace employé à chaque étape du traitement."},
{"instruction": "Puis-je être refusé ?", "output": "Oui, si les critères d’éligibilité ou de solvabilité ne sont pas remplis."},
{"instruction": "Quelles sont les causes fréquentes de refus ?", "output": "Absence de documents, situation bancaire non saine, ancienneté insuffisante, projet non cohérent avec le type de crédit."},
{"instruction": "Est-ce que je peux faire un crédit pour un membre de ma famille ?", "output": "Non, le crédit doit être directement lié à vos propres besoins."},
{"instruction": "Est-ce que le taux est négociable ?", "output": "Non, les taux sont fixes et définis par la politique interne de Talan."},
{"instruction": "Existe-t-il une assurance obligatoire ?", "output": "Non, mais une assurance emprunteur est fortement recommandée, notamment pour les prêts immobiliers."},
{"instruction": "Que faire si je perds ma fiche de paie ?", "output": "Vous pouvez demander une copie au service RH."},
{"instruction": "Quelle est la mensualité pour un crédit auto de 20 000 TND sur 5 ans ?", "output": "Avec un taux de 3%, cela équivaut à environ 359 TND/mois (simulation à confirmer)."},
{"instruction": "Quel est l’âge minimum pour bénéficier du crédit ?", "output": "Vous devez avoir au moins 18 ans et être en contrat actif chez Talan."},
{"instruction": "Puis-je choisir ma date de prélèvement ?", "output": "Oui, lors de la signature du contrat, vous pouvez choisir la date mensuelle."},
{"instruction": "Le crédit est-il renouvelable ?", "output": "Non, un nouveau crédit ne peut être demandé qu’après remboursement total de l’ancien."},
{"instruction": "Est-ce que je peux annuler ma demande ?", "output": "Oui, tant que le contrat n’a pas été signé, la demande peut être annulée sans frais."},
{"instruction": "Les crédits sont-ils soumis à l’approbation d’une banque ?", "output": "Non, le crédit est géré exclusivement en interne par Talan."},
{"instruction": "Comment le crédit est-il versé ?", "output": "Les fonds sont versés sur le compte bancaire indiqué après validation finale du dossier."},
{"instruction": "Est-ce que le taux change avec l’ancienneté ?", "output": "Non, les taux sont fixes et indépendants de l’ancienneté."},
{"instruction": "Qui puis-je contacter pour avoir plus d’informations ?", "output": "Le service RH ou votre référent financier est à votre disposition pour toute question."},
{"instruction": "Je n’ai pas de facture, puis-je quand même faire une demande ?", "output": "Une attestation de besoin ou un devis est obligatoire pour justifier le crédit."},
{"instruction": "Quelles informations dois-je fournir dans la demande ?", "output": "Montant demandé, durée souhaitée, type de crédit, coordonnées bancaires, pièce justificative du projet."},
{"instruction": "Le crédit figure-t-il sur mon bulletin de salaire ?", "output": "Oui, la mensualité est prélevée directement et visible sur votre fiche de paie."},
{"instruction": "Quel est le plafond maximum pour chaque crédit ?", "output": "Le plafond dépend de votre revenu mensuel net et du type de crédit. Simulation recommandée."},
{"instruction": "Puis-je demander un crédit sans relevé bancaire ?", "output": "Non, les trois derniers relevés bancaires sont obligatoires."}


]

# 🔍 Recherche exacte
def find_answer_exact(user_question):
    cleaned_user = nettoyer(user_question)
    for item in faq_data:
        if nettoyer(item["instruction"]) == cleaned_user:
            return item["output"]
    return None

# 🔍 Recherche floue avec difflib
def find_answer_fuzzy(user_question):
    cleaned_question = nettoyer(user_question)
    questions = [item["instruction"] for item in faq_data]
    cleaned_questions = [nettoyer(q) for q in questions]

    closest_match = difflib.get_close_matches(cleaned_question, cleaned_questions, n=1, cutoff=0.3)
    if closest_match:
        index = cleaned_questions.index(closest_match[0])
        return faq_data[index]["output"]
    return None

# 🌐 Endpoint API
@app.route('/chat', methods=['POST'])
def chat():
    user_input = request.json.get("question", "")
    response = find_answer_exact(user_input)
    if not response:
        response = find_answer_fuzzy(user_input)
    if not response:
        response = "Désolé, je n’ai pas compris votre question."
    return jsonify({"response": response})

@app.route('/', methods=['GET'])
def home():
    return "✅ Chatbot FAQ is running. Use POST /chat with a JSON body {\"question\": \"...\"}"


# 🔁 Démarrage avec port dynamique pour Render
if __name__ == '__main__':
    import os
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)