from flask import Flask, request, jsonify
from flask_cors import CORS
import difflib
import unicodedata

app = Flask(__name__)
CORS(app)

def nettoyer(text):
    text = text.lower().strip()
    text = ''.join(
        c for c in unicodedata.normalize('NFD', text)
        if unicodedata.category(c) != 'Mn'
    )
    return text

# ✅ Données FAQ
faq_data = [
    {"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Puis-je modifier le montant après la demande ?", "output": "Oui, avant la validation finale."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Y a-t-il une ancienneté minimale requise ?", "output": "Oui, une ancienneté de 6 mois est recommandée."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Comment téléverser mes documents ?", "output": "Connectez-vous à l’espace client, allez dans ‘Mes crédits’ et cliquez sur ‘Téléverser mes documents’."},
{"instruction": "Puis-je refuser le devis proposé ?", "output": "Oui, vous pouvez le refuser ou demander une nouvelle simulation."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Qui peut bénéficier d’un crédit chez Talan ?", "output": "Les salariés en contrat actif ayant terminé leur période d’essai."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Comment se passe la négociation ?", "output": "Un conseiller vous contactera par téléphone ou via la plateforme."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que faire si la durée demandée est trop longue ?", "output": "Le gestionnaire vous proposera des alternatives ajustées à votre profil."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que se passe-t-il après la signature du contrat ?", "output": "Le montant est débloqué et transféré dans un délai de 48 heures."},
{"instruction": "Puis-je annuler un contrat signé ?", "output": "Non, une fois signé, le contrat engage les deux parties."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Puis-je envoyer mes documents par email ?", "output": "Non, seuls les documents téléversés via la plateforme sont pris en compte."},
{"instruction": "Faut-il un revenu minimum pour demander un crédit ?", "output": "Oui, un revenu net mensuel supérieur à 1200 TND est requis."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Comment suivre ma demande de crédit ?", "output": "Dans l’espace client, rubrique ‘Suivi des crédits’."},
{"instruction": "Comment signer le contrat de crédit ?", "output": "Une fois le devis accepté, le contrat est signé électroniquement sur la plateforme."},
{"instruction": "Que faire si un document est refusé ?", "output": "Vous recevrez une notification pour téléverser un document conforme."},
{"instruction": "Quand recevrai-je le devis ?", "output": "Une fois la demande validée et la négociation terminée."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je demander plusieurs crédits à la fois ?", "output": "Non, une seule demande active est autorisée."},
{"instruction": "Mes documents doivent-ils être au format PDF ?", "output": "Oui, les fichiers PDF ou JPEG sont acceptés."},
{"instruction": "Que faire si je change de compte bancaire ?", "output": "Mettez à jour vos coordonnées dans votre espace personnel."},
{"instruction": "Qu’est-ce qu’un devis de crédit ?", "output": "C’est une estimation détaillée du crédit proposé, incluant le montant, la durée et les mensualités."},
{"instruction": "Quels documents dois-je fournir pour une demande de crédit ?", "output": "Carte d’identité, fiche de paie des 3 derniers mois, relevé bancaire, justificatif de résidence."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Qui analyse les documents envoyés ?", "output": "Notre équipe spécialisée en crédit examine chaque dossier manuellement."},
{"instruction": "Comment recevoir les notifications importantes ?", "output": "Activez les alertes dans vos paramètres de profil."},
{"instruction": "Puis-je négocier le montant du crédit ?", "output": "Oui, une négociation est possible si le montant dépasse le plafond autorisé."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."},
{"instruction": "Puis-je demander un crédit si je suis stagiaire ?", "output": "Non, seuls les salariés sous contrat sont éligibles."},
{"instruction": "Qui contacter en cas de problème ?", "output": "Vous pouvez écrire au support via le formulaire de contact."},
{"instruction": "Combien de temps prend l’analyse des documents ?", "output": "En moyenne 24 à 48 heures ouvrées."}

]

def find_answer_exact(user_question):
    cleaned_user = nettoyer(user_question)
    for item in faq_data:
        if nettoyer(item["instruction"]) == cleaned_user:
            return item["output"]
    return None

def find_answer_fuzzy(user_question):
    cleaned_question = nettoyer(user_question)
    questions = [item["instruction"] for item in faq_data]
    cleaned_questions = [nettoyer(q) for q in questions]

    closest_match = difflib.get_close_matches(cleaned_question, cleaned_questions, n=1, cutoff=0.6)
    if closest_match:
        score = difflib.SequenceMatcher(None, cleaned_question, closest_match[0]).ratio()
        if score >= 0.6:
            index = cleaned_questions.index(closest_match[0])
            return faq_data[index]["output"]
    return None

@app.route('/chat', methods=['POST'])
def chat():
    user_input = request.json.get("question", "")
    response = find_answer_exact(user_input)
    if not response:
        response = find_answer_fuzzy(user_input)
    if not response:
        response = "Désolé, je n’ai pas compris votre question."
    return jsonify({"response": response})

@app.route('/', methods=['GET'])
def home():
    return "✅ Chatbot FAQ is running. Use POST /chat with a JSON body {\\\"question\\\": \\\"...\\\"}"

if __name__ == '__main__':
    import os
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)

# Écriture dans un fichier .py
output_path = "/mnt/data/chatbot_faq_corrected.py"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(chatbot_code)

output_path